#
# Macro file for the initialization phase of "LXe.cc"
# when runing in interactive mode
#
# Sets some default verbose
#
/run/verbose 2
/control/verbose 2
#
# Create a scene handler/viewer for a specific graphics system
#    The compound command "/vis/open <vis-driver-name>"
#    is equivalent to the following set of commands:
#
#    /vis/sceneHandler/create
#    /vis/viewer/create
#
# Create a scene handler and a viewer for the OGLIX driver
##/vis/open OGLIX
#
##/vis/viewer/set/style wireframe
# Set direction from target to camera.
#/vis/viewer/set/viewpointVector 1 1.5 1.1
##/vis/viewer/set/viewpointThetaPhi 60 120 deg
#/vis/viewer/zoom 1.4
#
#    The compound command "/vis/drawVolume"
#    is equivalent to the following set of commands:
#
#    /vis/scene/create
#    /vis/scene/add/volume
#    /vis/sceneHandler/attach
# Create an empty scene and add the detector geometry to it
##/vis/drawVolume
#
# Store particle trajectories for visualization
# (if too many tracks cause core dump => storeTrajectory 0)
/tracking/storeTrajectory 4
#
# Add trajectories to the current scene
# Note: This command is not necessary since the C++ method DrawTrajectory()
#       is called in LXeEventAction::EndOfEventAction
##/vis/scene/add/trajectories
#
# Requests viewer to accumulate hits, tracks, etc. at end of event.
# detector remains or is redrawn.
##/vis/scene/endOfEventAction accumulate
#/MuONe/detector/PMTefficiency mppc-25.eff
/MuONe/generator/position 0. 0. -70.
/MuONe/detector/dimensions 4. 4. 0.5
/MuONe/detector/housingThickness 2.
/MuONe/detector/nfibers 0
#/MuONe/detector/slabz 2.
#/MuONe/detector/volumes/wls 1
/MuONe/detector/update
/MuONe/eventVerbose 0
/MuONe/recorder/filename "prova.root"
/gun/particle mu-
/gun/energy 150. GeV
/run/beamOn 20000000